### ISSUE TITLE
portmap documentation

### ISSUE THREAD

**Issue by kris-brown** [AlgebraicJulia/AlgebraicDynamics.jl#114]
Hi, for creating Resource Sharers, the API docs show there is a final argument called `portmap`, though this is not provided explictly by the first few examples I saw in Examples. Is it possible to add a note for what it means and when to write it explicitly?

**Comment by slibkind** [comment]
Great point! I added some documentation in PR #115. Do you think that clarifies the useage of `portmap`.

**Comment by kris-brown** [comment]
Very clear, thanks!
