### ISSUE TITLE
Support for models with delays?

### ISSUE THREAD

**Issue by sdwfrost** [AlgebraicJulia/AlgebraicDynamics.jl#41]
I'm curious as to your thoughts on how delays could get represented in the framework- see e.g. [https://github.com/epirecipes/sir-julia/blob/master/markdown/dde/dde.md](https://github.com/epirecipes/sir-julia/blob/master/markdown/dde/dde.md) for a simple model with a delay.

**Comment by jpfairbanks** [comment]
I think that you could add delays with a type of system that has two variables where it reads from one variable and then holds that value for T seconds before writing it to the other variable. However, this looks like a much better way. We would define a new `oapply` https://diffeq.sciml.ai/dev/tutorials/dde_example/ following the instructions at this link.
