### ISSUE TITLE
Add support for labelled arrays

### ISSUE THREAD

**Issue by slibkind** [AlgebraicJulia/AlgebraicDynamics.jl#58]
Allow user to specify the state as a labelled array. Each machine will contain not just a number of states but the labels for the states as well. Readouts can be specified by label.

**Comment by slibkind** [comment]
When adding labels for ResourceSharers improve interoperation between AlgebraicPetri and AlgebraicDynamics by ensuring that the labels on LabelledPetriNets are preserved

**Comment by jpfairbanks** [comment]
This was done #73 and then removed in #142 because LArray is deprecated in favor of ComponentArrays.
