### ISSUE TITLE
better use of variable names in docs

### ISSUE THREAD

**Issue by slwu89** [AlgebraicJulia/AlgebraicDynamics.jl#77]
This is a very small "issue", but in section 3 of Composing Dynamical Systems on the main docs page https://github.com/AlgebraicJulia/AlgebraicDynamics.jl/blob/master/docs/src/index.md the variable *p* is used to refer to the port map on one line, and is then reused on the following line to refer to the dynamics function's parameters. I'd suggest using something else for one of these two.

**Comment by slibkind** [comment]
Thanks for the catch! Fixed in PR #63
